development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  channel_prefix: mesto_development

test:
  adapter: test

production:
  <% redis_options = Mesto::RedisConnection.options %>
  adapter: redis
  url: <%= redis_options.fetch(:url) %>
  <% if redis_options[:ssl_params] %>
  ssl_params:
    verify_mode: <%= redis_options.dig(:ssl_params, :verify_mode) %>
  <% end %>
  channel_prefix: mesto_production
